{
 "title": "Kubernetes / Controller Manager",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_cpu_seconds_total{cluster=\"$cluster\", job=\"kube-controller-manager\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\", job=\"kube-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{cluster=\"$cluster\", job=\"kube-controller-manager\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{cluster=\"$cluster\", job=\"kube-controller-manager\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{cluster=\"$cluster\", job=\"kube-controller-manager\", instance=~\"$instance\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"kube-controller-manager\", instance=~\"$instance\", verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"kube-controller-manager\", instance=~\"$instance\", verb=\"GET\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=\"$cluster\", job=\"kube-controller-manager\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\", job=\"kube-controller-manager\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\", job=\"kube-controller-manager\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}